---
title: "Exercicio 6"
author: "Kaíque Pereira Santos"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Neste exercício usaremos o banco de dados do ESEB 2018. Para maiores detalhes sobre o survey, ver neste [link](https://www.cesop.unicamp.br/por/eseb).
### O questionário da pesquisa de 2018 está [aqui](https://www.cesop.unicamp.br/vw/1IMr0S64wNQ_MDA_91ea3_/quest_04622.pdf) e pode ser consultado para ter
### maiores detalhes sobre as variáveis.


library( haven )
library( tidyverse )
library( observer )
library( tibble )


### O banco de dados está disponível no site do CESOP para usuários cadastrados. Para facilitar o acesso, deixei o banco de dados dispónivel no seguinte
### endereço:

# https://github.com/MartinsRodrigo/Analise-de-dados/raw/master/04622.sav

### Baixe o banco de dados pelo R


url <- "https://github.com/MartinsRodrigo/Analise-de-dados/raw/master/04622.sav"

download.file( url, "banco_ex6.sav", mode = "wb" )


### O banco foi feito em SPSS e está em formato SAV. Carregue-o

banco <- read_sav( "banco_ex6.sav" )

write_sav( banco, "banco.sav" )



### Utilize as funções para observar o banco de dados


banco
glimpse( banco )
summary( banco )
str( banco )
head( banco )
tail( banco )
observe( banco )


### A variável Q1607 indica uma nota de 0 a 10 ao candidato Jair Bolsonaro. Valores acima de 10 representam respostas não uteis para nossa pesquisa. Repre-
### sente graficamente esta variável apenas com os valores válidos e descreva o resultado.*OBS: transforme esta variável para númerica com a função
### `as.numeric()`.


banco$Q1607

banco_Q1607 <- banco %>% mutate( Q1607 = as.numeric( Q1607 ) ) %>%
               group_by( Q1607 ) %>%
               filter( Q1607 <= 10 )

ggplot( banco_Q1607, aes( Q1607 ) ) +
        geom_histogram( )

ggplot( banco_Q1607, aes( Q1607, "" ) ) +
        geom_violin( )


# DESCRIÇÃO: a variável Q1607, a qual é discreta, representa uma escala a qual é usada para representar a intensidade com a qual as pessoas gostam de Jair
#            Bolsonaro. Antes da filtragem, tal escala ia de 0 à 10 e de 96 à 99, onde o primeiro intervalo demonstra o quanto a pessoa gosta do político,
#            e o segundo intervalo demonstra que a pessoa não conhece, não respondeu ou não sabe avaliar. Após a filtragem, mantém-se apenas os valores de
#            0 à 10. De acordo com o histograma, existem um pouco mais de 500 pessoas que não gostam de Bolsonaro de jeito nenhum, e um pouco mais que 600
#            que gostam muito, enquanto boa parte se encontra entre esses dois extremos. Entre 2 e 5, temos, para cada valor, menos de 100 observações. A
#            partir do valor 5, e com excessão do 6, todos os valores são acima de 100. Em suma, há uma ligeira tendência de apoio ao presidente.

### Vamos procurar entender o que está associado à aprovação deste candidato. Primeiro, vamos observar a idade dos respondentes com a variável D1A_ID.
### Represente esta variável graficamente.



max( banco_Q1607$D1A_ID )

ggplot( banco_Q1607, aes( D1A_ID ) ) +
        geom_histogram( binwidth = 0.9, colour = "black", fill = "grey" )

ggplot( banco_Q1607, aes( D1A_ID ) ) +
        geom_boxplot( )


### Teste a associação entre a nota dada a Jair Bolsonaro e idade do respondente, explicando o resultado.


cor.test( banco_Q1607$Q1607, banco_Q1607$D1A_ID )


# RESPOSTA: De acordo com o teste de correlação, existe uma associação positiva e significante entre as duas variáveis. Com o p-valor baixíssimo de 1.235e-06,
#           podemos rejeitar a hipótese nula de que não há relação entre as variáveis, i.e., de que a correlação entre as variáveis teria valor igual à 0.
#           O intervalo de 95% de confiança é inteiramente positivo, i.e., não contém o valor 0, indo de 0.0599 à 0.1404. Isso reforça a rejeição da hipótese
#           nula. O valor da correlação para essa amostra é de 0.10003613.


### Faça uma regressao linear mostrando em que medida a idade do respondente explica a avaliação do candidato Jair Bolsonaro. Interprete o resultado.


ggplot( banco_Q1607, aes( D1A_ID, Q1607 ) ) +
        geom_point( ) +
        geom_smooth( method = "lm" )

regressao_Q1607_D1A <- lm( Q1607 ~ D1A_ID, data = banco_Q1607 )

summary( regressao_Q1607_D1A )
confint( regressao_Q1607_D1A, level = 0.95 )

# INTERPRETAÇÃO: Na regressão, temos o intercepto, i.e., o alfa, que representa o valor que a variável dependente tem quando a variável independente é igual
#                à zero, tem valor de 4.473878, valor o qual é estatísticamente significativo, dado que o p-valor é baixíssimo, de 2e-16, possibilitando re-
#                jeitar a hipótese nula de que esse coeficiente tem valor igual  à zero. Sobre o beta, i.e., D1A_ID, esse é o coeficiente angular da equação,
#                o qual representa o impacto que uma variação na variável independente causa na variação da variável dependente. Aqui, D1A_ID tem valor de
#                0.025534. Isso significa que, caso mudemos D1A_ID em 1 unidade, alteraremos Q1607 em 0.025534. O p-valor de D1A_ID também é baixíssimo, de
#                1.24e-06, demonstrando que o valor de D1A_ID é estatísticamente significante, i.e., não é igual à 0. O erro residual padrão é de 3.951. Ele
#                representa a distância média entre os valores das observações e o valor da linha de regressão. Aqui, ele é bem alto, considerando que Q1607
#                vai de 0 a 10. O R quadrado, o qual representa o quanto a variável independente explica a variação na variável dependente, é baixo,
#                de 0.01007, i.e., 1%, deixando claro que esse modelo tem baixo valor explicativo. Segundo confint, podemos ter 95% de confiança de que o va-
#                lor do intercept se encontra entre 4.021 e 4.92, e que o valor de D1A_ID se encontra entre 0.01523 e 0.03583.


### Observe a variável D3_ESCOLA dos respondentes relativa a educação Represente esta variável graficamente. #OBS: observe que esta variável está como numérica,
### apesar de ser categórica ordinal. No entanto, trate-a como numérica, indicando que quanto maior o valor, maior o nível educacional do respondente.

str( banco_Q1607$D3_ESCOLA )
min( banco_Q1607$D3_ESCOLA )
max( banco_Q1607$D3_ESCOLA )

ggplot( banco_Q1607, aes( D3_ESCOLA ) ) +
        geom_bar( )

### Teste a associação entre a nota dada a Jair Bolsonaro e educação do respondente, explicando o resultado.

cor.test( banco_Q1607$Q1607, banco_Q1607$D3_ESCOLA )

# RESPOSTA: Segundo o teste de correlação, existe uma correlação negativa e estatísticamente signficante entre as variáveis. O p-valor foi baixo, de 0.001114,
#           de modo que podemos rejeitar a hipótese nula, a qual afirma não haver relação entre as variáveis, com um alto grau de confiança. Além do mais, o
#           intervalo de confiança de 95% é inteiramente negativo, i.e., não inclui o 0, o que confirmaria a hipótese nula. Tal intervalo vai de -0.1079 à
#           -0.0269. A estimação da amostra é de -0.06755, valor o qual se encontra dentro do intervalo especificado.

### Faça uma regressao linear mostrando em que medida a educação do respondente explica a avaliação do candidato Jair Bolsonaro. Interprete o resultado.

ggplot( banco_Q1607, aes( D3_ESCOLA, Q1607 ) ) +
        geom_point( ) +
        geom_smooth( method = "lm" )

regressao_Q1607_D3 <- lm( Q1607 ~ D3_ESCOLA, data = banco_Q1607 )
summary( regressao_Q1607_D3 )
confint( regressao_Q1607_D3 )

# INTERPRETAÇÃO: O intercepto, alfa, coeficiente linear e valor que a variável dependente tem quando a variável independente é igual à zero, tem valor de
#                6.10223, a um p-valor baixissimo de 2e-16, o que permite a rejeição da hipótese nula de que o coeficiente tem valor igual à zero. D3_ESCOLA,
#                o beta e coeficiente angular, tem valor de -0.11835, a um p-valor baixo de 0.00111, o que também permite rejeitar a hipótese nula de que seu
#                valor seria 0. Cada unidade variada em D3_ESCOLA provoca uma variação de -0.11835, o que corresponde com a correlação negativa entre as va-
#                riáveis, apresentada no teste de correlação. O erro residual padrão é alto, de 3.962, considerando que a variável dependente vai de 0 a 10.
#                O R quadrado é bem baixo, de 0.004564, i.e., 0,4%, deixando claro que D3_ESCOLA explica pouco a variação em Q1607. Segundo confint, para um
#                intervalor de confiança de 95%, temos que o valor do intercepto esta entre 5.71 e 6.48, e o valor de D3_ESCOLA está entre -0.18 e -0.04.
#                Ambos os valores correspondem aos achados da regressão linear.

### Observe a variável D9 sobre renda dos respondentes. Represente esta variável graficamente. #OBS: note que os valores 9999998 e 9999999 devem ser
### descartados.

banco_D9 <- banco_Q1607 %>% group_by( D9 ) %>%
            filter( D9 != 9999998 && D9 != 9999999 )

str( banco_D9$D9 )
min( banco_D9$D9 )
max( banco_D9$D9 )

ggplot( banco_D9, aes( D9 ) ) +
        geom_histogram( )

ggplot( banco_D9, aes( D9 ) ) +
        geom_boxplot( )

### Teste a associação entre a nota dada a Jair Bolsonaro e renda do respondente, explicando o resultado.

cor.test( banco_D9$Q1607, banco_D9$D9 )

# RESPOSTA: A correlação entre as variáveis não é estatisticamente significante. O p-valor é extremamtena alto, de 0.8474, o que não nos possibilita
#           rejeitar a hipótese nula, de que não há correlação entre as variáveis. Outro fator que indica a invalidade da correlação observada é o fato
#           de que o intervalo de confiança de 95% contém 0, já que tal intervalo vai de -0.0415 à 0.0505. A estimativa da amostra é de 0.00451955, i.e.,
#           bem próximo de 0, indicando a invalidade da correlação.

### Faça uma regressao linear mostrando em que medida a renda do respondente explica a avaliação do candidato Jair Bolsonaro. Interprete o resultado.

ggplot( banco_D9, aes( D9, Q1607 ) ) +
        geom_point( ) +
        geom_smooth( method = "lm" )

regressao_Q1607_D9 <- lm( Q1607 ~ D9, data = banco_D9 )
summary( regressao_Q1607_D9 )
confint( regressao_Q1607_D9 )

# INTERPRETAÇÃO: A regressão linear corrobora com os resultados da correlação. O intercepto, alfa e coeficiente linear, tem valor de 5.578e+00, a um
#                p-valor baixíssimo de 2e-16, possibilitando a rejeição da hipótese nula, segundo a qual o valor do intercepto seria 0. O coefici-
#                ente angular, ou beta, tem valor baixíssimo de -5.857e-06, a um p-valor alto de 0.847, o que demonstra a insignificância estatística
#                do resultado, impossibilitando a rejeição da hipótese nula, segundo a qual tal coeficiente teria valor 0. O erro residual padrão tem valor
#                de 3.959, e o R quadrado tem valor de 2.043e-05, demonstrando o baixo valor explicativo desse modelo, já que a variável independen-
#                te só dá conta de explicar um valor próximo de 0 da variação no valor da variável dependente aqui. O baixo valor do coeficiente angular
#                e o baixo valor do R quadrado deixam claro que D9 não é relevante para explicar Q1607. Confint, para 95% de confiança, corrobora com ambos
#                os coeficientes, já que o valor desses se encontram dentro dos intervalos especificados. I.e., o intercepto com valor 5.578e+00 está
#                dentro de 5.338700e+00 e 5.817597e+00, e D9 com valor de 5.857e-06 está dentro de --5.383427e-05 e 6.554816e-05.

### Deixando as variáveis socio-economicas de lado, vamos analisar agora variáveis relativas a preferências políticas.

### A variável Q1501 indica uma nota de 0 a 10 ao PT. Valores acima de 10 representam respostas não uteis para nossa pesquisa. Represente graficamente esta
### variável apenas com os valores válidos e descreva o resultado.

banco_Q1501 <- banco_Q1607 %>% filter( Q1501 <= 10 )

ggplot( banco_Q1501, aes( Q1501 ) ) +
        geom_histogram( )

ggplot( banco_Q1501, aes( Q1501, "" ) ) +
        geom_violin( )

# DESCRIÇÃO: Basicamente, o que esses gráfico mostram é que as pessoas odeiam o PT. Temos mais de 875 observações no valor 0, o qual computa as pessoas que
#            não gostam de jeito nenhum do PT, enquanto, com exceção dos valores 5 e 10, todos os outros valores estão no máximo em 125 observações. 5 e
#            10 possuem, respectivamente,  quase 250 e quase 375 observações. Isso significa que poucas pessoas gostam, em algum nível, do PT.

### Teste a associação entre a nota dada a Jair Bolsonaro e a nota dada ao PT, explicando o resultado.

cor.test( banco_Q1501$Q1501, banco_Q1501$Q1607 )

# RESPOSTA: De acordo com o resultado do teste correlação, podemos afirmar que há correlação entre as variáveis. Além do p-valor extremamente baixo, de
#           2.2e-16, o que indica que podemos imediatamente rejeitar a hipótese nula, de que não há relação entre as variáveis, temos também o fato do
#           intervalo de confiança não conter o valor 0, já que vai de -0.432 à -0.36182. As estimativas da amostra são de -0.39754. Isso indica que a
#           relação entre as variáveis é negativa, i.e., o aumento em uma é acompanhado de uma diminuição na outra. Essa correlação é teoricamente supor-
#           tada pelo fato de que o PT e o partido de Bolsonaro estão em posições ideológicas bem afastadas uma da outra.

### Faça uma regressao linear mostrando em que medida a nota dada ao PT pelo respondente explica a avaliação do candidato Jair Bolsonaro. Interprete o
### resultado.

ggplot( banco_Q1501, aes( Q1501, Q1607 ) ) +
        geom_point( ) +
        geom_smooth( method = "lm" )

regressao_Q1607_Q1501 <- lm( Q1607 ~ Q1501, data = banco_Q1501 )
summary( regressao_Q1607_Q1501 )
confint( regressao_Q1607_Q1501 )

# INTERPRETAÇÃO: A regressao corrobora com os resultados apresentados na correlação. O intercepto, ou alfa e coeficiente linear, tem valor de 7.001 quando
#                a variável independente é igual a 0. Isso com um p-valor baixíssimo, de 2e-16, demonstrando a significância estatística do resultado e a
#                confiança de que o valor do intercepto não é igual à zero. O coeficiente angular, ou beta, Q1501, tem valor de -0.41118, a um p-valor bai-
#                xíssimo de 2e-16, o que também demonstra a significância estatistica desse coeficiente, de modo que possamos rejeitar a hipótese de que
#                ele seria igual à zero. O erro residual padrao é alto, de 3.643, considerando que a escala da variável dependente vai de 0 a 10. E o R
#                quadrado do modelo é alto, de 0.158, i.e., a variável independente explica 15% da variação na variável dependente. I.e., tem um razoável
#                poder explicativo. Confint reforça a significância dos valores dos coeficientes, dado que o valor do intercepto se encontra dentro do in-
#                tervalo de confiança de 95%, o qual vai de 6.79 à 7.21, e que Q1501 se encontra dentro de -0.4508 e -0.3715. O valor do coeficiente angu-
#                lar, ou beta, é bem alto, sugerindo que variações na variável independente provocam boas variações nos valores da variável dependente.

### A variável Q18 indica uma auto-atribuição em uma escala ideologica de 0 a 10, da esquerda para a direita. Valores acima de 10 representam respostas não
### uteis para nossa pesquisa. Represente graficamente esta variável apenas com os valores válidos e descreva o resultado.

banco_Q18 <- banco_Q1607 %>% filter( Q18 <= 10 )

max( banco_Q18$Q18 )

ggplot( banco_Q18, aes( Q18 ) ) +
        geom_histogram( )

# DESCRIÇÃO: A variável Q18 mede o posicionamento de uma pessoa na escala ideológica, indo de 0 a 10. Valores mais próximos de 0 indicam que a pessoa é ou
#            tende à esquerda. Valores próximos de 5 indicam que a pessoa é ou tende a ser de centro, e, similarmente, valores próximos à 10 indicam que a 
#            pessoa é ou tende à direita. De acordo com o gráfico, temos um pouco mais de 200 pessoas que se consideram de esquerda, um pouco mais de 300
#            pessoas que se consideram de centro, e um pouco mais de 600 pessoas que se consideram de direita. Valores entre 0 e 5 estão abaixo das 100 ob-
#            servações, e, com exceção do valor 8, o qual tem quase 200 observações, valores entre 5 e 10 também estão abaixo das 100 observações. Entre-
#            tanto, observa-se uma tendência à direita.

### Teste a associação entre a nota dada a Jair Bolsonaro e a auto-atribuição ideológica, explicando o resultado.

cor.test( banco_Q18$Q1607, banco_Q18$Q18 )

# RESPOSTA: A correlação suporta um resultado esperado, i.e., que exista uma relação positiva entre as variáveis, dado que, como foi visto no gráfico, há
#           uma tendência à direita, posição ideológica na qual se encontra o presidente. Segundo a correlação, a qual é positiva, temos um resultado esta-
#           tísticamente significante, dado o p-valor baixíssimo de 2.2e-16, o que nos permite rejeitar a hipótese nula, e o fato de que o intervalo de con-
#           fiança de 95% ser inteiramente positivo, i.e., não conter o 0, indo de 0.3133 à 0.3927. A estimativa da amostra é de 0.3567.

### Faça uma regressao linear mostrando em que medida a auto-atribuição ideológica do repondente explica a avaliação do candidato Jair Bolsonaro. Interprete
### o resultado.

ggplot( banco_Q18, aes( Q18, Q1607 ) ) +
        geom_point( ) +
        geom_smooth( method = "lm" )

regressao_Q1607_Q18 <- lm( Q1607 ~ Q18, data = banco_Q18 )
summary( regressao_Q1607_Q18 )
confint( regressao_Q1607_Q18 )

# RESPOSTA: A regressão linear corrobora com o resultado do teste de correlação. O intercepto, ou alfa, tem valor de 3.006, a um p-valor baixíssimo de 2e-16,
#           indicando a significância estatística do valor do intercepto e que este não é igual à 0. Além do mais, Q18, ou beta, tem valor alto de 0.409, i.e.,
#           cada unidade alterada na variável independente muda em 0.40941 o valor da variável dependente. Esse coeficiente também é estatisticamente signi-
#           ficante, dado que seu p-valor é baixíssimo, de 2e-16, permitindo que rejeitemos a hipótese nula, segundo a qual ele teria valor 0. O erro residual
#           padrão é alto, de 3.695, considerando que a escala da variável dependente é de 0 a 10. E o R quadrão é razoável, de 0.1251. Isso significa que essa
#           variável independente explica 12.51% da variação nos valores da variável dependente. Confint confirma a validade dos valores dos coeficientes, dado
#           que os mesmos se encontram dentro dos intervalos de 95% de confiança, os quais vão de 2.642 à 3.37, para o intercepto, e 0.36 à 0.458, para Q18.

### Observando o resultado das regressões, você diria que qual tipo de variável explica mais a variação das notas atribuidas a Jair Bolsonaro, as
### socio-economicas ou políticas?

summary( lm( Q1607 ~ Q1501 + Q18, data = ( banco %>% filter( Q1607 <= 10, Q1501 <= 10, Q18 <= 10 ) ) ) )

summary( lm( Q1607 ~ D1A_ID + D3_ESCOLA + D9, data = ( banco %>% filter( Q1607 <= 10, D9 != 9999998 && D9 != 9999999 ) ) ) )

# RESPOSTA: As variáveis políticas explicam mais. Os resultados das regressões envolvendo Q1607, Q1501 e Q18 apresentaram uma forte relação entre Q1607, como
#           variável dependente, e Q1501 e Q18 como independentes. Essas duas variáveis políticas explicam bastante o valor de Q1607. Q1501 influencia negati-
#           vamente no valor de Q1607, enquanto Q18 influencia positivamente no valor desta última, e ambas tem R quadrado de valor razoável, sendo o R quadra-
#           do de Q1501 = 0.15 e o R quadrado de Q18 = 0. 1251, i.e., Q1501 explica 15% e Q18 explicar 12.51%. D1A_ID, D3_ESCOLA e D9 influenciam pouquíssimo
#           ou nada no valor de Q1607, tendo R quadrado de D1A_ID = 0.01007, D3_ESCOLA = 0.004564 e D9 = 2.043e-05. D9, segundo o teste de correlação, sequer
#           tem relação estatisticamente significante com Q1607, enquanto as outras duas, apesar de terem alguma relação, essa relação é baixíssima, com coe-
#           ficientes angulares pequenos, e R quadrado baixos.

### Observando o resultado das regressões, você diria que algum modelo errou menos comparado aos outros na nota prevista atribuída a Jair Bolsonaro?

# RESPOSTA: Observando os erros residuais padrãp de todas as variáveis, temos o seguinte ordenamento dos erros: D1A_ID = 3.951, D3_ESCOLA = 3.962, D9 = 3.959, 
#           Q1501 = 3.643, Q18 = 3.695. Logo, Q1501 < Q18 < D1A_ID < D0 < D3_ESCOLA. Logo, o modelo de regressão envolvendo Q1607 e Q1501 é o que erra
#           menos. Esse é o modelo que mede o efeito de gostar ou não do PT sobre gostar ou não de Bolsonaro.

### Observando o resultado das regressões, você diria que qual(quais) variáveis possui(em) maior efeito no nota atribuída a Jair Bolsonaro?

# RESPOSTA: As variáveis Q1501 e Q18. Q1501 influencia negativamente na nota atribuída a Jair Bolsonaro, impactando em -0.41118 em Q1607, para cada unidade
#           variada em Q1501, variação a qual explica 15%, segundo o R quadrado, da variação em Q1607. Já Q18 influencia positivamente, alterando em 0.40941
#           Q1607 a cada unidade variada em Q18. Além do mais, o R quadrado de Q18 foi de 0.1251, i.e., variações em Q18 explicam 12.51% das variações em
#           Q1607.
```