---
title: "Exercicio 5"
author: "Kaique Pereira Santos"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Carregue o banco de dados `world` que está no pacote `poliscidata`.

```{r}
library( poliscidata )

banco <- world



### Carregue o banco de dados `world` que está no pacote `poliscidata`.

library( tidyverse )
library( poliscidata )

banco <- world


### Existem diversas medidas de democracia para os países: `dem_score14`, `democ11`, `fhrate04_rev`,
### `fhrate08_rev`, `polity`. Descreva-as graficamente e diga quais são as diferenças entre tais medidas.

?world

min( banco$dem_score14, na.rm = T )
max( banco$dem_score14, na.rm = T )
str( banco$dem_score14 )
ggplot( banco, aes( dem_score14 ) ) +
        geom_histogram( aes( y = ..density.. ), colour = "white", fill = "grey" ) +
        geom_density( colour = "red" )

min( banco$democ11, na.rm = T )
max( banco$democ11, na.rm = T )
str( banco$democ11 )
ggplot( banco, aes( democ11 ) ) +
        geom_bar( )

min( banco$fhrate04_rev, na.rm = T )
max( banco$fhrate04_rev, na.rm = T )
str( banco$fhrate04_rev )
ggplot( banco, aes( fhrate04_rev ) ) +
        geom_bar( )

min( banco$fhrate08_rev, na.rm = T )
max( banco$fhrate08_rev, na.rm = T )
str( banco$fhrate08_rev )
ggplot( banco, aes( fhrate08_rev ) ) +
        geom_boxplot( )

min( banco$polity, na.rm = T )
max( banco$polity, na.rm = T )
str( banco$polity )
ggplot( banco, aes( polity ) ) +
        geom_bar( )

# RESPOSTA: dem_score14 é uma variável numérica contínua, ou seja, é representada por número reais. democ11
#           é uma variável numérica discreta, i.e., representa valores inteiros, indo de 0 a 10. Essas duas
#           variáveis medem o nível de democracia em um país, variando de menos para mais a medida que os
#           valores crescem. fhrate04_rev é uma variável contínua, em um intervalo de 1 a 7, enquanto 
#           fhrate08_rev é discreta, indo de 0 a 12. As duas são índices elaborados pela Freedom House para
#           representar graus de democracia. Por último, polity também é usada para medir nível de democracia
#           em um país. Ela é uma variável discreta, mas, diferentemente das outras variáveis discretas, ela
#           pode assumir valores negativos. Seu intervalo vai de -10 até 10.
  
### Avalie a relação entre todas as medidas de democracia e desigualdade, utilizando a variável
### `gini08`. Descreva graficamente esta variável, a relação entre as duas variáveis, meça a correla-
### ção entre elas e faça regressões lineares (interpretando em profundidade os resultados dos coefi-
### cientes e medidas de desempenho dos modelos). Enfatize as semelhanças e diferenças entre os resul-
### tados. Quais são suas conclusões?

# Descrever graficamente gini08
ggplot( banco, aes( gini08 ) ) +
        geom_histogram( aes( y = ..density.. ), colour = "white", fill = "grey" ) +
        geom_density( colour = "black" )

# descrever graficamente relação entre gini e dem_score14
ggplot( banco, aes( gini08, dem_score14 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gini dem_score14
cor.test( banco$gini08, banco$dem_score14 )

# regressão gini dem_score14
reg_gini_dem14 <- lm( dem_score14 ~ gini08, data = banco )
summary( reg_gini_dem14 )

# INTERPRETAÇÃO: A correlação entre as duas variáveis é negativa, ou seja, existe uma relação inversa entre as
#                duas variáveis. Quanto maior o valor de gini08, menor o valor de dem_score14. Como o p-valor
#                é baixo e como o intervalo de confiança de 95% indica que o coeficiente de correlação está
#                entre dois valores negativos, -0.3821 e -0.0432, podemos concluir que o valor da correlação
#                não é zero, e, portanto, rejeita a hipótese nula de que não há relação entra as variáveis.
#                Quanto à regressão linear, ambos os p-valores, do intercepto e de gini08, são bem baixos, porém,
#                o do intercepto é menor. O p-valor menor para o intercepto indica um maior nível de confiança de
#                que o valor do intercepto é ou está bem próximo de 7.17 quando gini08 for igual a 0. O efeito 
#                estimado de gini08 sobre dem_score14 é de -0.04448. Isso significa que qualquer variação x no
#                valor de gini08 provoca uma variação de -0.04448 * x no valor de dem_score14. Por último, o R
#                quadrado está bem baixo, 0.04809, demonstrando o baixo valor explicativo do modelo.

# descrever graficamente relação entre gini e democ11
ggplot( banco, aes( gini08, democ11 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gini democ11
cor.test( banco$gini08, banco$democ11 )

# regressão gini democ11
reg_gini_dem11 <- lm( democ11 ~ gini08, data = banco )
summary( reg_gini_dem11 )

# INTERPRETAÇÃO: Aqui, vários fatores indicam que a relação entre as duas variáveis é muito possivelmente ine-
#                inexistente. O p-valor de 0.3677 é muito alto, e o intervalo de confiança varia de negativo
#                para positivo, -0.263 e 0.099, deixando claro que um dos possíveis valores do intervalo é 0.
#                Ambos os fatores reforçam a hipótese nula, a qual indica que não existe relação entre as va-
#                riáveis. Essa conclusão é reforçada pela regressão linear, pois o p-valor de gini08 é de 0.368
#                e o impacto baixíssimo de -0.02994 que cada variação em gini08 tem sobre democ11. O único valor
#                significativo aqui é o do intercepto, que é de 7.68 com um p-valor bem baixo. O erro residual
#                padrão, que representa a distância média entre os valores das observações e o valor do intercepto,
#                tem valor alto de 3.47, e o poder explicativo nesse modelo é de R² = 0.007186, que é muito baixo.

# descrever graficamente relação entre gini e fhrate04_rev
ggplot( banco, aes( gini08, fhrate04_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gini fhrate04_rev
cor.test( banco$gini08, banco$fhrate04_rev )

# regressão gini fhrate04_rev
reg_gini_fh04 <- lm( fhrate04_rev ~ gini08, data = banco )
summary( reg_gini_fh04 )

# INTERPRETAÇÃO: O p-valor razoável de 0.04921 e o intervalo, com 95% de confiança, entre -0.3452 e -0.0007, deixam
#                claro que há sim uma correlação negativa entre as variáveis. O fato de o p-valor ser baixo e o in-
#                tervalo não incluir o valor 0 indicam que a correlação observada é significativa de modo que podemos
#                com alguma confiança rejeitar a hipótese nula de que não há relação entre as variáveis.. Na regressão, 
#                vemos que o intercepto tem valor 6.136 com um p-valor baixíssimo, demonstrando boa confiabilidade
#                no resultado. O impacto de gini08 em fhrate04_rev é negativo e baixo, de -0.0319, com um p-valor de
#                0.0492, o qual garante também boa confiabilidade no resultado. O erro residual padrão é de 1.786 e
#                o R quadrado é baixo, de 0.03185, demonstrando que o modelo tem pouco poder explicativo.

# descrever graficamente relação entre gini e fhrate08_rev
ggplot( banco, aes( gini08, fhrate08_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gini fhrate08_rev
cor.test( banco$gini08, banco$fhrate08_rev )

# regressão gini fhrate08_rev
reg_gini_fh08 <- lm( fhrate08_rev ~ gini08, data = banco )
summary( reg_gini_fh08 )

# INTERPRETAÇÃO: Na correlação, dado o p-valor um pouco mais alto, de 0.08387, e o fato do intervalo com 95% de significância 
#                possivelmente incluir o valor 0, já que vai de -0.327 a 0.0212, não podemos concluir que há uma relação
#                significativa entre as variáveis, e, portanto, também não podemos rejeitar imediatamente a hipótese nula.
#                No que diz respeito à regressão linear, temos o intercepto com valor 9.97288 a um p-valor baixíssimo, o
#                qual apresenta três asteriscos. gini08, de acordo com a regressão, tem impacto baixo e negativo de -0.0559,
#                a um p-valor ligeiramente mais alto de 0.0839. O erro residual padrão é ligeiramente mais alto, de 3.554, e
#                o R quadrado é bem baixo, 0.0249, deixando claro o baixo poder explicativo do modelo.

# descrever graficamente relação entre gini e polity
ggplot( banco, aes( gini08, polity ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gini polity
cor.test( banco$gini08, banco$polity )

# regressão gini polity
reg_gini_pol <- lm( polity ~ gini08, data = banco )
summary( reg_gini_pol )

# INTERPRETAÇÃO: Na correlação, temos um p-valor bem alto, de 0.665, e um intervalo de confiança de 95% entre -0.222 e 0.14,
#                no qual está presente o valor 0. Isso indica que não há correlação signficativa entre as variáveis.
#                Esses dois fatores indicam que não podemos imediatamente rejeitar a hipótese nula para essa relação.
#                Na regressão, temos o intercepto com valor 6.21813 a um p-valor bem baixo, de 0.00569. Quanto à va-
#                riável gini08, essa tem impacto negativo baixíssimo na variável polity, de -0.02292, acompanhado de
#                um p-valor bem alto de 0.66499. O erro residual padrão é alto, de 5.535, e o R quadrado é extrema-
#                mente baixo, de 0.001665, o que deixa claro o baixo poder explicativo do modelo.

# CONCLUSÃO: Todos os resultados deixam claro que é baixa ou inexistente a relação entre gini08 e as medidas de democracia
#            nos países. Apenas dois dos resultados, dem_score14 e fhrate04_rev, apresentaram valores estatísticamente sig-
#            nificantes, e mesmo assim, foram baixos e negativos. Os outros três resultados simplesmente não apresentaram
#            significância, demonstrando que gini08 não impacta em democ11, fhrate08_rev, e polity. Em suma, não podemos
#            dizer que gini08 afeta democracia de maneira muito forte.

### Avalie a relação entre todas as medidas de democracia e crescimento econômico, utilizando a vari-
### ável `gdppcap08`. Descreva graficamente esta variável, a relação entre as duas variáveis, meça a
### correlação entre elas e faça regressões lineares (interpretando em profundidade os resultados dos
### coeficientes e medidas de desempenho dos modelos). Enfatize as semelhanças e diferenças entre os
### resultados. Quais são suas conclusões?

# Descrever graficamente gdppcap08
ggplot( banco, aes( gdppcap08 ) ) +
        geom_boxplot( )

# descrever graficamente relação entre gdppcap08 e dem_score14
ggplot( banco, aes( gdppcap08, dem_score14 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gdppcap08 dem_score14
cor.test( banco$gdppcap08, banco$dem_score14 )

# regressão gdppcap08 dem_score14
reg_gdp_dem14 <- lm( dem_score14 ~ gdppcap08, data = banco )
summary( reg_gdp_dem14 )

# INTERPRETAÇÃO: A correlação entre gdppcap08 e dem_score14 é positiva e significativa, dado que o p-valor
#                é extremamente baixo e o intervalo de confiança de 95%, inteiramente positivo, vai de 0.3763 a
#                0.615, ou seja, não inclui 0. A regressão linar tem intercepto 4.678e+00, com p-valor
#                extremamente pequeno, de 2e-16, mostrando a robustez do resultado. Tem também gdppcap08
#                com valor positivo de 7.040e-05 e p-valor extremamente pequeno, de 3.16e-11. Esses valores
#                baixos em ambos os p-valor deixam claro a significância dos resultados. O erro residual padrão
#                tem valor de 1.864, e o R quadrado tem valor alto de 0.2553, mostrando que o poder explicativo
#                desse modelo é grande, i.e., gdppcap08 é responsável por uma boa parcela da variação em dem_score14.

# descrever graficamente relação entre gdppcap08 e democ11
ggplot( banco, aes( gdppcap08, democ11 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gdppcap08 democ11
cor.test( banco$gdppcap08, banco$democ11 )

# regressão gdppcap08 democ11
reg_gdp_dem11 <- lm( democ11 ~ gdppcap08, data = banco )
summary( reg_gdp_dem11 )

# INTERPRETAÇÃO: O teste de correlação apresenta resultados significativos, dado que o p-valor é bem baixo, de
#                0.000435, e que o intervalo de confiança de 95% é inteiramente positivo, ou seja, não inclui 0,
#                indo de 0.1330 a 0.4351. A correlação também é positiva. No que diz respeito à regressão linear,
#                temos p-valor baixo para ambos os intercepto e gdppcap08, sendo o primeiro menor que o segundo.
#                Isso deixa claro que ambos o intercepto e gdppcap08 são estatísticamente significantes. O intercepto
#                tem valor de 4.939e+00 e gdppcap08 tem valor de 7.359e-05. O erro residual padrão, i.e., a distância
#                média entre os valores das observações e a linha de regressão, é alto, de 3.57. O R quadrado é razoa-
#                velmente baixo, de 0.08489, mostrando o baixo valor explicativo que esse modelo tem.

# descrever graficamente relação entre gdppcap08 e fhrate04_rev
ggplot( banco, aes( gdppcap08, fhrate04_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gdppcap08 fhrate04_rev
cor.test( banco$gdppcap08, banco$fhrate04_rev )

# regressão gdppcap08 fhrate04_rev
reg_gdp_fh04 <- lm( fhrate04_rev ~ gdppcap08, data = banco )
summary( reg_gdp_fh04 )

# INTERPRETAÇÃO: A correlação entre as duas variáves é positiva e significativa, com um intervalo de confiança de 95%
#                inteiramente positivo, indo de 0.302 a 0.560. O p-valor é baixíssimo, de 1.331e-08, mostrando a sig-
#                nificância do resultado e a possibilidade de se rejeitar a hipótese nula. No que diz respeito à re-
#                gressão, temos ambos intercepto e gdppcap08 com valores estatísticamente significantes. O intercepto
#                tem valor de 3.828e+00, a um p-valor de 2e-16, e gdppcap08 tem valor de 5.545e-05, a um p-valor de
#                1.33e-08, ambos com três asteriscos. O erro residual padrão é ligeiramente alto, de 1.751, mostrando
#                que os valores das observações tem distância média não muito alta da reta de regressão, e o R quadrado
#                tem valor de 0.1942, alto, mostrando que é razoável o poder explicativo desse modelo.

# descrever graficamente relação entre gdppcap08 e fhrate08_rev
ggplot( banco, aes( gdppcap08, fhrate08_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gdppcap08 fhrate08_rev
cor.test( banco$gdppcap08, banco$fhrate08_rev )

# regressão gdppcap08 fhrate08_rev
reg_gdp_fh08 <- lm( fhrate08_rev ~ gdppcap08, data = banco )
summary( reg_gdp_fh08 )

# INTERPRETAÇÃO: A correlação entre as duas variáveis é positiva e estatísticamente significativa. Temos um intervalo
#                de 95% de confiança inteiramente positivo, i.e., não inclui 0, indo de 0.30611 a 0.56385, com um
#                p-valor de 1.115e-08, evidenciando a possibilidade de se rejeitar a hipótese nula. No que diz respeito
#                à regressão linear, ela reforça essa relação estatística. O intercepto tem valor de 5.698e+00, a um
#                p-valor de 2e-16, enquanto gdppcap08 tem valor de 1.098e-04, a um p-valor de 1.11e-08. Ambos os p-
#                valor são baixíssimos, indicando a significância estatística das duas variáveis. O erro residual padrão
#                tem valor de 3.438, o que é ligeiramente alto, e o R quadrado tem valor alto de 0.1973, mostrando que
#                o modelo tem bom poder explicativo.

# descrever graficamente relação entre gdppcap08 e polity
ggplot( banco, aes( gdppcap08, polity ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação gdppcap08 polity
cor.test( banco$gdppcap08, banco$polity )

# regressão gdppcap08 polity
reg_gdp_pol <- lm( polity ~ gdppcap08, data = banco )
summary( reg_gdp_pol )

# INTERPRETAÇÃO: A correlação entre as duas variáveis é positiva e estatísticamente significativa. Temos um intervalo
#                de 95% de confiança inteiramente positivo, indo de 0.004758 à 0.32501, com um p-valor de 0.04392, o
#                qual é baixo. No que diz respeito à regressão linear, ela reforça ligeiramente essa relação estatística.
#                Temos um intercepto com valor de 3.374e+00, com p-valor baixo de 2.2e-06, e temos gdppcap08 com valor
#                baixo de 7.047e-05, com um p-valor de 0.0439, tendo apenas um asterisco. O erro residual padrão é razoa-
#                velmente alto, de 6.059, e o R qadrado é baixo, de 0.02868, demonstrando o baixo poder explicativo de
#                gdppcap08 sobre polity. 

# CONCLUSÃO: Com excessão do impacto de gdppcap08 sobre polity, o qual foi positivo porém baixo, todas as outras relações
#            entre gdppcap08 e dem_score14, democ11, fhrate04_rev e fhrate08_rev, foram também positivas, porém bem mais
#            fortes. Podemos concluir que renda per capta, como medida de desenvolvimento econômico, tem um bom impacto
#            sobre sobre os níveis de democracia, de modo que valores mais altos de gdppcap08 estejam associados a valores
#            mais altos nos índices de democracia.

### Avalie a relação entre todas as medidas de democracia e produção de petróleo, utilizando a variá-
### vel `oil`. Descreva graficamente esta variável, a relação entre as duas variáveis, meça a corre-
### lação entre elas e faça regressões lineares (interpretando em profundidade os resultados dos co-
### eficientes e medidas de desempenho dos modelos). Enfatize as semelhanças e diferenças entre os
### resultados. Quais são suas conclusões?

# Descrever graficamente oil
ggplot( banco, aes( oil ) ) +
        geom_histogram( )

# descrever graficamente relação entre oil e dem_score14
ggplot( banco, aes( oil, dem_score14 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil dem_score14
cor.test( banco$oil, banco$dem_score14 )

# regressão oil dem_score14
reg_oil_dem14 <- lm( dem_score14 ~ oil, data = banco )
summary( reg_oil_dem14 )

# INTERPRETAÇÃO: Não podemos dizer que a correlação entre as duas variáveis é estatísticamente significativa. Isso acontece
#                por dois fatores: o intervalo de 95% de confiança varia entre valores negativos e positivos, i.e., inclui
#                0, indo de -0.2744 à 0.02631, e o p-valor é bem alto, sendo igual a 0.1041, indicando a possibilidade de
#                aceitarmos a hipótese nula. No que diz respeito à regressão linear, ela reforça os achados da correlação.
#                O intercepto tem valor de 5.654e+00, com p-valor baixíssimo, de 2e-16, três asteriscos. Já oil tem valor
#                de -1.881e-07, ou seja, influencia pouquíssimo em dem_score14, e tem p-valor alto de 0.104. O erro residual
#                padrão é razoável, de 2.177, e o R quadrado é de 0.01612, ou seja, deixando claro o baixo valor explicativo
#                do modelo, em termos do quão bem oil explica variações em dem_score14.

# descrever graficamente relação entre oil e democ11
ggplot( banco, aes( oil, democ11 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil democ11
cor.test( banco$oil, banco$democ11 )

# regressão oil democ11
reg_oil_dem11 <- lm( democ11 ~ oil, data = banco )
summary( reg_oil_dem11 )

# INTERPRETAÇÃO: Não podemos dizer que a correlação entre as duas variáveis é estatísticamente significativa. Isso acontece
#                por dois fatores: o intervalo de confiança de 95% varia entre valores negativos e positivos, i.e., inclui
#                0, indo de -0.2992 à 0.02138, e o p-valor é ligeiramente alto, sendo 0.0879, indicando a possibilidade de
#                aceitarmos a hipótese nula. No que diz respeito à regressão linear, ela reforça os resultados da correlação.
#                O intercepto tem valor de 6.139e+00, com p-valor baixíssimo de 2e-16, três asteriscos. Já oil tem valor muito
#                baixo, de -3.402e-07, influenciando poquíssimo em democ11, e tem p-valor ligeiramente alto, de 0.088. O erro
#                residual é razoavelmente alto, de 3.685, e o R quadrado é baixíssimo, de 0.02036, deixando claro o baixo valor
#                explicativo do modelo. 

# descrever graficamente relação entre oil e fhrate04_rev
ggplot( banco, aes( oil, fhrate04_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil fhrate04_rev
cor.test( banco$oil, banco$fhrate04_rev )

# regressão oil fhrate04_rev
reg_oil_fh04 <- lm( fhrate04_rev ~ oil, data = banco )
summary( reg_oil_fh04 )

# INTERPRETAÇÃO: Na correlação, apesar do p-valor de 0.0562, i.e., um p-valor razoável, não podemos dizer que a correlação é
#                estatísticamente significante, dado que o intervalo de confiança de 95% inclui o valor 0. Portanto, não po-
#                demos rejeitar a hipótese nula. No que diz respeito à regressão linear, ela reforça os resultados da corre-
#                lação. O intercepto tem valor de 4.675e+00, com p-valor baixíssimo de 2e-16, três asteriscos. Já oil tem
#                valor baixíssimo e negativo de -1.990e-07, mostrando o fraco impacto na variação de fhrate04_rev, com p-valor
#                razoável de 0.0562. O erro residual padrão é razoável, de 1.934, e o R quadrado é baixo, de 0.02409, deixando
#                claro o baixo valor de oil como explicador da variação em fhrate04_rev.

# descrever graficamente relação entre oil e fhrate08_rev
ggplot( banco, aes( oil, fhrate08_rev ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil fhrate08_rev
cor.test( banco$oil, banco$fhrate08_rev )

# regressão oil fhrate08_rev
reg_oil_fh08 <- lm( fhrate08_rev ~ oil, data = banco )
summary( reg_oil_fh08 )

# INTERPRETAÇÃO: Na correlação, apesar do p-valor de 0.06235, o qual é ligeiramente alto, não podemos dizer que a correlação
#                é estatísticamente significante, dado que o intervalo de confiança de 95% inclui o valor 0. Portanto, não
#                podemos rejeitar a hipótese nula. No que diz respeito à regressão linear, ela reforça os resultados da cor-
#                relação. O intercepto tem valor de 7.378e+00, com p-valor baixíssimo de 2e-16. Já oil tem valor negativo e
#                baixíssimo de -3.824e-07, mostrando o fraco impacto na variação de fhrate08_rev, com p-valor de 0.0624. O 
#                erro residual padrão é alto, de 3.526, e o R quadrado é baixo, de 0.02312, deixando claro o baixo valor 
#                explicativo do modelo.

# descrever graficamente relação entre oil e polity
ggplot( banco, aes( oil, polity ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil polity
cor.test( banco$oil, banco$polity )

# regressão oil polity
reg_oil_pol <- lm( polity ~ oil, data = banco )
summary( reg_oil_pol )

# INTERPRETAÇÃO: A correlação entre as duas variáveis é negativa e estatísticamente significante. Temos um intervalo de con-
#                fiança de 95% inteiramente negativo, indo de -0.3348 à -0.01811. Portanto, podemos rejeitar a hipótese nula.
#                A regressão linear tem intercepto com valor de 4.752e+00, a um p-valor baixíssimo de 2.09e-15. Já oil tem
#                valor negativo baixíssimo de -7.105e-07, com p-valor bom de 0.0298. O erro residual padrão tem valor alto de
#                6.024, e o R quadrado é baixo, de 0.03282, deixando claro o baixo valor explicativo do modelo.

# CONCLUSÃO: Com exceção da relação entre polity e oil, todas as outras relações entre oil e dem_score14, democ11, fhrate04_rev
#            e fhrate08_rev são fracas e sem significância estatística. Isso significa que a produção de petróleo tem pouca
#            relação com alterações nos níveis de democracia nos países. Ou seja, produção de petróleo não explica variação
#            de grau em níveis de democracia.

### Avalie a relação entre crescimento econômico e produção de petróleo. Descreva a relação entre as
### duas variáveis, meça a correlação entre elas e faça regressões lineares (interpretando em profun-
### didade os resultados dos coeficientes e medidas de desempenho dos modelos). Enfatize as semelhan-
### ças e diferenças entre os resultados. Quais são suas conclusões?

ggplot( banco, aes( oil ) ) +
        geom_boxplot( )

ggplot( banco, aes( gdppcap08 ) ) +
        geom_histogram( aes( y = ..density.. ), colour = "white", fill = "grey" ) +
        geom_density( colour = "red" )

# Descrever graficamente oil e gdppcap08
ggplot( banco, aes( oil, gdppcap08 ) ) +
        geom_point( ) +      
        geom_smooth( method = "lm" )

# correlação oil gdppcap08
cor.test( banco$oil, banco$gdppcap08 )

# regressão oil gdppcap08
reg_oil_gdp <- lm( gdppcap08 ~ oil, data = banco )
summary( reg_oil_gdp )

# INTERPRETAÇÃO: A correlação entre as duas variáveis é estatisticamente significante. Temos um intervalo de confiança de
#                95% inteiramente positivo, i.e., não inclui 0, e com valores que vão de 0.02661 à 0.0335. O p-valor é baixo,
#                com valor de 0.02254. Esses dois fatores deixam claro que podemos rejeitar a hipótese nula. No que diz res-
#                peito à regressão, ela corrobora com o resultado da correlação. O intercepto tem valor de 1.262e+04, com p-
#                valor baixíssimo de 2e-16, e oil tem valor baixo 1.884e-03, com p-valor bem baixo de 0.0225, tendo um aste-
#                isco. O erro residual padrão é de 15280, dada a escala alta dos valores das observações, e o R quadrado é
#                baixo, de 0.03443, deixando claro o baixo valor explicativo do modelo.

# CONCLUSÃO: Existe sim uma relação entre produção de petróleo e desenvolvimento econômico, medido em termos da renda per
#            capta. Como a renda per capta é calculada em termos do PIB e do tamanho da população, e como produção de pe-
#            tróleo afeta o PIB de um país, é totalmente compreensível que a produção de petróleo também afete a renda per
#            capta do país.

### A partir das suas conclusões sobre a relação entre democracia, economia e produção de petróleo,
### quais considerações são possíveis fazer sobre a relação CAUSAL entre estas variáveis? Lembre dos
### 4 "hurdles" do livro *Fundamentals of Political Science Research*

# RESPOSTA: De acordo com o livro de Kellstedt e Whitten, os 4 hurdles são considerações que devemos ter sobre a relação
#           entre as variáveis às quais pretendemos atribuir valor causal. Os 4 hurdles são:

#           1. Mecanismo conectando X à Y?
#           2. Podemos eliminar causalidade reversa?
#           3. Existe covariação entre X e Y?
#           4. Controlamos por todas as confounders Z que podem afetar a relação entre X e Y?

#           Para o ponto 4, dificilmente, usando testes que envolvem apens duas variáveis, podemos ter controlados por
#           todos os tipos de confounders que poderiam afetar as relações exploradas. 

#           Para o ponto 3, vimos que há covariação entre somente entre duas medidas de democracia e o indíce de gini08,
#           ou seja, em 3 dos 5 casos apenas 2 apresentaram covariação, portanto, podemos eliminar a possibilidade de 
#           relação causal nesses 3 casos. Na relação entre renda per capta e democracia, todas as relações apresentam
#           covariação, de modo que não podemos aqui eliminar a possibilidade de relação causal. Na relação entre demo-
#           cracia e produção de petróleo, apenas uma relação apresentou covariação, de modo que podemos eliminar a pos-
#           sibilidade de relação causal nos outros 4 casos. E, por último, há covariação entre produção de petróleo e
#           desenvolvimento econômico, de modo que não podemos eliminar a possibilidade de relação causal entre as duas.

#           Para o ponto 2, não podemos eliminar a possibilidade de relação causal reversa entre democracia e desigualdade,
#           democracia e desenvolvimento econômico, e desenvolvimento econômico e produção de petróleo. Porém, podemos eli-
#           minar a possibilidade de causalidade reversa entre democracia e produção de petróleo, já que não é evidente como
#           regimes mais ou menos democráticos afetam a produção de petróleo, dado que existe países, principalmente no
#           oriente médio, pouco democráticos mas que estão entre os principais produtores de petróleo do mundo.

#           Para o ponto 1, a diminuição da desigualdade pode afetar a democracia ao equilibrar os poderes entre os cidadão.
#           Não existem mecanismos evidente de como renda per capta ou produção de petróleo podem afetar o nível de democracia.
#           Quanto à relação entre pib per capta e produção de petróleo, a produção de petróleo afeta o PIB, o qual é usado
#           como base para o cálculo do PIB per capta. Logo, produção de petróleo diretamente afeta desenvolvimento econômico.
```